package service

import "errors"

var (
	ErrEmailVacio              = errors.New("El campo Email es obligatorio")
	ErrPasswordVacio           = errors.New("La contraseña es obligatoria")
	ErrNombreVacio             = errors.New("El campo Nombre no puede estar vacío o estar vacío")
	ErrTituloVacio             = errors.New("El campo Titulo no puede estar vacío")
	ErrTipoViviendaVacio       = errors.New("El campo Tipo de Vivienda no puede estar vacío")
	ErrPrecioVacio             = errors.New("El campo Precio no puede estar vacío")
	ErrGarantiaVacia           = errors.New("El campo Garantia no puede estar vacío")
	ErrPrecioGarantiaVacio     = errors.New("El campo Precio de Garantia no puede estar vacío")
	ErrLuzVacia                = errors.New("El campo Luz no puede estar vacío")
	ErrAguaVacia               = errors.New("El campo Agua no puede estar vacío")
	ErrAmuebladoVacio          = errors.New("El campo Amueblado no puede estar vacío")
	ErrInternetVacio           = errors.New("El campo Internet no puede estar vacío")
	ErrBañoPrivadoVacio        = errors.New("El campo Baño Privado no puede estar vacío")
	ErrNumeroHabitacionesVacio = errors.New("El campo Número de Habitaciones no puede estar vacío")
	ErrMascotasVacia           = errors.New("El campo Mascotas no puede estar vacío")
	ErrGeneroPreferidoVacio    = errors.New("El campo Genero Preferido no puede estar vacío")
	ErrReglasConvivenciaVacio  = errors.New("El campo Reglas de Convivencia no puede estar vacío")
	ErrTelefonoVacio           = errors.New("El campo Teléfono no puede estar vacío")
	ErrComentarioVacio         = errors.New("El campo Comentario no puede estar vacío")
	ErrEstadoVacio             = errors.New("El campo Estado no puede estar vacío")
	ErrURLVacio                = errors.New("El campo URL no puede estar vacío")
	ErrNoEncontrado            = errors.New("No se encontró la vivienda")
	ErrEmailEnUso              = errors.New("El campo Email ya está en uso")
	ErrCredencialesInvalidas   = errors.New("Email o contraseña no son válidos")
)
