// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type Alimentacion struct {
	ID              int64
	NombreLocal     string
	Descripcion     string
	Ubicacion       string
	Direccion       string
	HorarioApertura string
	HorarioCierre   string
	Telefono        string
	TipoComida      string
	PrecioPromedio  float64
	ProviderID      int64
}

type AplicarVivienda struct {
	AplicarViviendaID int64
	EstudianteID      int64
	ViviendaID        int64
	Estado            string
}

type Cooperativa struct {
	ID          int64
	Nombre      string
	Telefono    string
	Descripcion string
}

type Foto struct {
	FotoID     int64
	Url        string
	ViviendaID int64
}

type MenuDiario struct {
	ID             int64
	Fecha          string
	AlimentacionID int64
}

type ParadasBus struct {
	ID           int64
	NombreParada string
	Direccion    string
	Descripcion  string
}

type Plato struct {
	ID           int64
	NombrePlato  string
	Descripcion  string
	Categoria    string
	Precio       float64
	MenuDiarioID int64
}

type Resena struct {
	ID             int64
	Comentario     string
	Calificacion   int64
	AlimentacionID int64
}

type RutaTransporte struct {
	ID              int64
	NombreLinea     string
	FrecuenciaAprox string
	Precio          float64
	DescripcionRuta string
	CooperativaID   int64
	SectorOrigenID  int64
	SectorDestinoID int64
	ParadaBusID     int64
}

type Sector struct {
	SectorID int64
	Nombre   string
}

type Vivienda struct {
	ViviendaID         int64
	Titulo             string
	TipoVivienda       string
	Precio             float64
	Garantia           bool
	PrecioGarantia     float64
	Direccion          string
	Luz                bool
	Agua               bool
	Amueblado          bool
	Internet           bool
	BanoPrivado        bool
	NumeroHabitaciones int64
	Mascotas           bool
	GeneroPreferido    string
	ReglasConvivencia  string
	Telefono           string
	Email              string
	Estado             string
	Comentario         string
	SectorID           int64
	ProveedorID        int64
}
