// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const actualizarAlimentacion = `-- name: ActualizarAlimentacion :exec
UPDATE alimentacion SET
    nombre_local = ?, descripcion = ?, ubicacion = ?, direccion = ?,
    horario_apertura = ?, horario_cierre = ?, telefono = ?,
    tipo_comida = ?, precio_promedio = ?, provider_id = ?
WHERE id = ?
`

type ActualizarAlimentacionParams struct {
	NombreLocal     string
	Descripcion     string
	Ubicacion       string
	Direccion       string
	HorarioApertura string
	HorarioCierre   string
	Telefono        string
	TipoComida      string
	PrecioPromedio  float64
	ProviderID      int64
	ID              int64
}

func (q *Queries) ActualizarAlimentacion(ctx context.Context, arg ActualizarAlimentacionParams) error {
	_, err := q.db.ExecContext(ctx, actualizarAlimentacion,
		arg.NombreLocal,
		arg.Descripcion,
		arg.Ubicacion,
		arg.Direccion,
		arg.HorarioApertura,
		arg.HorarioCierre,
		arg.Telefono,
		arg.TipoComida,
		arg.PrecioPromedio,
		arg.ProviderID,
		arg.ID,
	)
	return err
}

const actualizarAplicarVivienda = `-- name: ActualizarAplicarVivienda :exec
UPDATE aplicar_vivienda SET
    estudiante_id = ?, vivienda_id = ?, estado = ?
WHERE aplicar_vivienda_id = ?
`

type ActualizarAplicarViviendaParams struct {
	EstudianteID      int64
	ViviendaID        int64
	Estado            string
	AplicarViviendaID int64
}

func (q *Queries) ActualizarAplicarVivienda(ctx context.Context, arg ActualizarAplicarViviendaParams) error {
	_, err := q.db.ExecContext(ctx, actualizarAplicarVivienda,
		arg.EstudianteID,
		arg.ViviendaID,
		arg.Estado,
		arg.AplicarViviendaID,
	)
	return err
}

const actualizarCooperativa = `-- name: ActualizarCooperativa :exec
UPDATE cooperativa SET
    nombre = ?, telefono = ?, descripcion = ?
WHERE id = ?
`

type ActualizarCooperativaParams struct {
	Nombre      string
	Telefono    string
	Descripcion string
	ID          int64
}

func (q *Queries) ActualizarCooperativa(ctx context.Context, arg ActualizarCooperativaParams) error {
	_, err := q.db.ExecContext(ctx, actualizarCooperativa,
		arg.Nombre,
		arg.Telefono,
		arg.Descripcion,
		arg.ID,
	)
	return err
}

const actualizarFoto = `-- name: ActualizarFoto :exec
UPDATE foto SET
    url = ?, vivienda_id = ?
WHERE foto_id = ?
`

type ActualizarFotoParams struct {
	Url        string
	ViviendaID int64
	FotoID     int64
}

func (q *Queries) ActualizarFoto(ctx context.Context, arg ActualizarFotoParams) error {
	_, err := q.db.ExecContext(ctx, actualizarFoto, arg.Url, arg.ViviendaID, arg.FotoID)
	return err
}

const actualizarMenuDiario = `-- name: ActualizarMenuDiario :exec
UPDATE menu_diario SET
    fecha = ?, alimentacion_id = ?
WHERE id = ?
`

type ActualizarMenuDiarioParams struct {
	Fecha          string
	AlimentacionID int64
	ID             int64
}

func (q *Queries) ActualizarMenuDiario(ctx context.Context, arg ActualizarMenuDiarioParams) error {
	_, err := q.db.ExecContext(ctx, actualizarMenuDiario, arg.Fecha, arg.AlimentacionID, arg.ID)
	return err
}

const actualizarPlato = `-- name: ActualizarPlato :exec
UPDATE plato SET
    nombre_plato = ?, descripcion = ?, categoria = ?,
    precio = ?, menu_diario_id = ?
WHERE id = ?
`

type ActualizarPlatoParams struct {
	NombrePlato  string
	Descripcion  string
	Categoria    string
	Precio       float64
	MenuDiarioID int64
	ID           int64
}

func (q *Queries) ActualizarPlato(ctx context.Context, arg ActualizarPlatoParams) error {
	_, err := q.db.ExecContext(ctx, actualizarPlato,
		arg.NombrePlato,
		arg.Descripcion,
		arg.Categoria,
		arg.Precio,
		arg.MenuDiarioID,
		arg.ID,
	)
	return err
}

const actualizarResena = `-- name: ActualizarResena :exec
UPDATE resena SET
    comentario = ?, calificacion = ?, alimentacion_id = ?
WHERE id = ?
`

type ActualizarResenaParams struct {
	Comentario     string
	Calificacion   int64
	AlimentacionID int64
	ID             int64
}

func (q *Queries) ActualizarResena(ctx context.Context, arg ActualizarResenaParams) error {
	_, err := q.db.ExecContext(ctx, actualizarResena,
		arg.Comentario,
		arg.Calificacion,
		arg.AlimentacionID,
		arg.ID,
	)
	return err
}

const actualizarRuta = `-- name: ActualizarRuta :exec
UPDATE ruta_transporte SET
    nombre_linea = ?, frecuencia_aprox = ?, precio = ?,
    descripcion_ruta = ?, cooperativa_id = ?,
    sector_origen_id = ?, sector_destino_id = ?, provider_id = ?
WHERE id = ?
`

type ActualizarRutaParams struct {
	NombreLinea     string
	FrecuenciaAprox string
	Precio          float64
	DescripcionRuta string
	CooperativaID   int64
	SectorOrigenID  int64
	SectorDestinoID int64
	ProviderID      int64
	ID              int64
}

func (q *Queries) ActualizarRuta(ctx context.Context, arg ActualizarRutaParams) error {
	_, err := q.db.ExecContext(ctx, actualizarRuta,
		arg.NombreLinea,
		arg.FrecuenciaAprox,
		arg.Precio,
		arg.DescripcionRuta,
		arg.CooperativaID,
		arg.SectorOrigenID,
		arg.SectorDestinoID,
		arg.ProviderID,
		arg.ID,
	)
	return err
}

const actualizarVivienda = `-- name: ActualizarVivienda :exec
UPDATE vivienda SET
    titulo = ?, tipo_vivienda = ?, precio = ?, garantia = ?,
    precio_garantia = ?, direccion = ?, luz = ?, agua = ?,
    amueblado = ?, internet = ?, bano_privado = ?,
    numero_habitaciones = ?, mascotas = ?, genero_preferido = ?,
    reglas_convivencia = ?, telefono = ?, email = ?,
    estado = ?, comentario = ?, sector_id = ?, proveedor_id = ?
WHERE vivienda_id = ?
`

type ActualizarViviendaParams struct {
	Titulo             string
	TipoVivienda       string
	Precio             float64
	Garantia           sql.NullInt64
	PrecioGarantia     float64
	Direccion          string
	Luz                sql.NullInt64
	Agua               sql.NullInt64
	Amueblado          sql.NullInt64
	Internet           sql.NullInt64
	BanoPrivado        sql.NullInt64
	NumeroHabitaciones int64
	Mascotas           sql.NullInt64
	GeneroPreferido    string
	ReglasConvivencia  string
	Telefono           string
	Email              string
	Estado             string
	Comentario         string
	SectorID           int64
	ProveedorID        int64
	ViviendaID         int64
}

func (q *Queries) ActualizarVivienda(ctx context.Context, arg ActualizarViviendaParams) error {
	_, err := q.db.ExecContext(ctx, actualizarVivienda,
		arg.Titulo,
		arg.TipoVivienda,
		arg.Precio,
		arg.Garantia,
		arg.PrecioGarantia,
		arg.Direccion,
		arg.Luz,
		arg.Agua,
		arg.Amueblado,
		arg.Internet,
		arg.BanoPrivado,
		arg.NumeroHabitaciones,
		arg.Mascotas,
		arg.GeneroPreferido,
		arg.ReglasConvivencia,
		arg.Telefono,
		arg.Email,
		arg.Estado,
		arg.Comentario,
		arg.SectorID,
		arg.ProveedorID,
		arg.ViviendaID,
	)
	return err
}

const crearAlimentacion = `-- name: CrearAlimentacion :exec
INSERT INTO alimentacion (
    nombre_local, descripcion, ubicacion, direccion,
    horario_apertura, horario_cierre, telefono,
    tipo_comida, precio_promedio, provider_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CrearAlimentacionParams struct {
	NombreLocal     string
	Descripcion     string
	Ubicacion       string
	Direccion       string
	HorarioApertura string
	HorarioCierre   string
	Telefono        string
	TipoComida      string
	PrecioPromedio  float64
	ProviderID      int64
}

func (q *Queries) CrearAlimentacion(ctx context.Context, arg CrearAlimentacionParams) error {
	_, err := q.db.ExecContext(ctx, crearAlimentacion,
		arg.NombreLocal,
		arg.Descripcion,
		arg.Ubicacion,
		arg.Direccion,
		arg.HorarioApertura,
		arg.HorarioCierre,
		arg.Telefono,
		arg.TipoComida,
		arg.PrecioPromedio,
		arg.ProviderID,
	)
	return err
}

const crearAplicarVivienda = `-- name: CrearAplicarVivienda :exec
INSERT INTO aplicar_vivienda (estudiante_id, vivienda_id, estado)
VALUES (?, ?, ?)
`

type CrearAplicarViviendaParams struct {
	EstudianteID int64
	ViviendaID   int64
	Estado       string
}

func (q *Queries) CrearAplicarVivienda(ctx context.Context, arg CrearAplicarViviendaParams) error {
	_, err := q.db.ExecContext(ctx, crearAplicarVivienda, arg.EstudianteID, arg.ViviendaID, arg.Estado)
	return err
}

const crearCooperativa = `-- name: CrearCooperativa :exec
INSERT INTO cooperativa (nombre, telefono, descripcion)
VALUES (?, ?, ?)
`

type CrearCooperativaParams struct {
	Nombre      string
	Telefono    string
	Descripcion string
}

func (q *Queries) CrearCooperativa(ctx context.Context, arg CrearCooperativaParams) error {
	_, err := q.db.ExecContext(ctx, crearCooperativa, arg.Nombre, arg.Telefono, arg.Descripcion)
	return err
}

const crearFoto = `-- name: CrearFoto :exec
INSERT INTO foto (url, vivienda_id)
VALUES (?, ?)
`

type CrearFotoParams struct {
	Url        string
	ViviendaID int64
}

func (q *Queries) CrearFoto(ctx context.Context, arg CrearFotoParams) error {
	_, err := q.db.ExecContext(ctx, crearFoto, arg.Url, arg.ViviendaID)
	return err
}

const crearMenuDiario = `-- name: CrearMenuDiario :exec
INSERT INTO menu_diario (fecha, alimentacion_id)
VALUES (?, ?)
`

type CrearMenuDiarioParams struct {
	Fecha          string
	AlimentacionID int64
}

func (q *Queries) CrearMenuDiario(ctx context.Context, arg CrearMenuDiarioParams) error {
	_, err := q.db.ExecContext(ctx, crearMenuDiario, arg.Fecha, arg.AlimentacionID)
	return err
}

const crearPlato = `-- name: CrearPlato :exec
INSERT INTO plato (
    nombre_plato, descripcion, categoria, precio, menu_diario_id
) VALUES (?, ?, ?, ?, ?)
`

type CrearPlatoParams struct {
	NombrePlato  string
	Descripcion  string
	Categoria    string
	Precio       float64
	MenuDiarioID int64
}

func (q *Queries) CrearPlato(ctx context.Context, arg CrearPlatoParams) error {
	_, err := q.db.ExecContext(ctx, crearPlato,
		arg.NombrePlato,
		arg.Descripcion,
		arg.Categoria,
		arg.Precio,
		arg.MenuDiarioID,
	)
	return err
}

const crearResena = `-- name: CrearResena :exec
INSERT INTO resena (comentario, calificacion, alimentacion_id)
VALUES (?, ?, ?)
`

type CrearResenaParams struct {
	Comentario     string
	Calificacion   int64
	AlimentacionID int64
}

func (q *Queries) CrearResena(ctx context.Context, arg CrearResenaParams) error {
	_, err := q.db.ExecContext(ctx, crearResena, arg.Comentario, arg.Calificacion, arg.AlimentacionID)
	return err
}

const crearRuta = `-- name: CrearRuta :exec
INSERT INTO ruta_transporte (
    nombre_linea, frecuencia_aprox, precio, descripcion_ruta,
    cooperativa_id, sector_origen_id, sector_destino_id, provider_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CrearRutaParams struct {
	NombreLinea     string
	FrecuenciaAprox string
	Precio          float64
	DescripcionRuta string
	CooperativaID   int64
	SectorOrigenID  int64
	SectorDestinoID int64
	ProviderID      int64
}

func (q *Queries) CrearRuta(ctx context.Context, arg CrearRutaParams) error {
	_, err := q.db.ExecContext(ctx, crearRuta,
		arg.NombreLinea,
		arg.FrecuenciaAprox,
		arg.Precio,
		arg.DescripcionRuta,
		arg.CooperativaID,
		arg.SectorOrigenID,
		arg.SectorDestinoID,
		arg.ProviderID,
	)
	return err
}

const crearVivienda = `-- name: CrearVivienda :exec
INSERT INTO vivienda (
    titulo, tipo_vivienda, precio, garantia, precio_garantia,
    direccion, luz, agua, amueblado, internet, bano_privado,
    numero_habitaciones, mascotas, genero_preferido, reglas_convivencia,
    telefono, email, estado, comentario, sector_id, proveedor_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CrearViviendaParams struct {
	Titulo             string
	TipoVivienda       string
	Precio             float64
	Garantia           sql.NullInt64
	PrecioGarantia     float64
	Direccion          string
	Luz                sql.NullInt64
	Agua               sql.NullInt64
	Amueblado          sql.NullInt64
	Internet           sql.NullInt64
	BanoPrivado        sql.NullInt64
	NumeroHabitaciones int64
	Mascotas           sql.NullInt64
	GeneroPreferido    string
	ReglasConvivencia  string
	Telefono           string
	Email              string
	Estado             string
	Comentario         string
	SectorID           int64
	ProveedorID        int64
}

func (q *Queries) CrearVivienda(ctx context.Context, arg CrearViviendaParams) error {
	_, err := q.db.ExecContext(ctx, crearVivienda,
		arg.Titulo,
		arg.TipoVivienda,
		arg.Precio,
		arg.Garantia,
		arg.PrecioGarantia,
		arg.Direccion,
		arg.Luz,
		arg.Agua,
		arg.Amueblado,
		arg.Internet,
		arg.BanoPrivado,
		arg.NumeroHabitaciones,
		arg.Mascotas,
		arg.GeneroPreferido,
		arg.ReglasConvivencia,
		arg.Telefono,
		arg.Email,
		arg.Estado,
		arg.Comentario,
		arg.SectorID,
		arg.ProveedorID,
	)
	return err
}

const eliminarAlimentacion = `-- name: EliminarAlimentacion :exec
DELETE FROM alimentacion
WHERE id = ?
`

func (q *Queries) EliminarAlimentacion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, eliminarAlimentacion, id)
	return err
}

const eliminarAplicarVivienda = `-- name: EliminarAplicarVivienda :exec
DELETE FROM aplicar_vivienda
WHERE aplicar_vivienda_id = ?
`

func (q *Queries) EliminarAplicarVivienda(ctx context.Context, aplicarViviendaID int64) error {
	_, err := q.db.ExecContext(ctx, eliminarAplicarVivienda, aplicarViviendaID)
	return err
}

const eliminarCooperativa = `-- name: EliminarCooperativa :exec
DELETE FROM cooperativa
WHERE id = ?
`

func (q *Queries) EliminarCooperativa(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, eliminarCooperativa, id)
	return err
}

const eliminarFoto = `-- name: EliminarFoto :exec
DELETE FROM foto
WHERE foto_id = ?
`

func (q *Queries) EliminarFoto(ctx context.Context, fotoID int64) error {
	_, err := q.db.ExecContext(ctx, eliminarFoto, fotoID)
	return err
}

const eliminarMenuDiario = `-- name: EliminarMenuDiario :exec
DELETE FROM menu_diario
WHERE id = ?
`

func (q *Queries) EliminarMenuDiario(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, eliminarMenuDiario, id)
	return err
}

const eliminarPlato = `-- name: EliminarPlato :exec
DELETE FROM plato
WHERE id = ?
`

func (q *Queries) EliminarPlato(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, eliminarPlato, id)
	return err
}

const eliminarResena = `-- name: EliminarResena :exec
DELETE FROM resena
WHERE id = ?
`

func (q *Queries) EliminarResena(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, eliminarResena, id)
	return err
}

const eliminarRuta = `-- name: EliminarRuta :exec
DELETE FROM ruta_transporte
WHERE id = ?
`

func (q *Queries) EliminarRuta(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, eliminarRuta, id)
	return err
}

const eliminarVivienda = `-- name: EliminarVivienda :exec
DELETE FROM vivienda
WHERE vivienda_id = ?
`

func (q *Queries) EliminarVivienda(ctx context.Context, viviendaID int64) error {
	_, err := q.db.ExecContext(ctx, eliminarVivienda, viviendaID)
	return err
}

const listarAlimentaciones = `-- name: ListarAlimentaciones :many

SELECT id, nombre_local, descripcion, ubicacion, direccion, horario_apertura, horario_cierre, telefono, tipo_comida, precio_promedio, provider_id FROM alimentacion
`

// ALIMENTACION --
func (q *Queries) ListarAlimentaciones(ctx context.Context) ([]Alimentacion, error) {
	rows, err := q.db.QueryContext(ctx, listarAlimentaciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alimentacion
	for rows.Next() {
		var i Alimentacion
		if err := rows.Scan(
			&i.ID,
			&i.NombreLocal,
			&i.Descripcion,
			&i.Ubicacion,
			&i.Direccion,
			&i.HorarioApertura,
			&i.HorarioCierre,
			&i.Telefono,
			&i.TipoComida,
			&i.PrecioPromedio,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarAplicarViviendas = `-- name: ListarAplicarViviendas :many

SELECT aplicar_vivienda_id, estudiante_id, vivienda_id, estado FROM aplicar_vivienda
`

// APLICAR VIVIENDA --
func (q *Queries) ListarAplicarViviendas(ctx context.Context) ([]AplicarVivienda, error) {
	rows, err := q.db.QueryContext(ctx, listarAplicarViviendas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AplicarVivienda
	for rows.Next() {
		var i AplicarVivienda
		if err := rows.Scan(
			&i.AplicarViviendaID,
			&i.EstudianteID,
			&i.ViviendaID,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarCooperativas = `-- name: ListarCooperativas :many

SELECT id, nombre, telefono, descripcion FROM cooperativa
`

// COOPERATIVAS --
func (q *Queries) ListarCooperativas(ctx context.Context) ([]Cooperativa, error) {
	rows, err := q.db.QueryContext(ctx, listarCooperativas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cooperativa
	for rows.Next() {
		var i Cooperativa
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Telefono,
			&i.Descripcion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarFotos = `-- name: ListarFotos :many

SELECT foto_id, url, vivienda_id FROM foto
`

// FOTOS --
func (q *Queries) ListarFotos(ctx context.Context) ([]Foto, error) {
	rows, err := q.db.QueryContext(ctx, listarFotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Foto
	for rows.Next() {
		var i Foto
		if err := rows.Scan(&i.FotoID, &i.Url, &i.ViviendaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarFotosPorVivienda = `-- name: ListarFotosPorVivienda :many
SELECT foto_id, url, vivienda_id FROM foto
WHERE vivienda_id = ?
`

func (q *Queries) ListarFotosPorVivienda(ctx context.Context, viviendaID int64) ([]Foto, error) {
	rows, err := q.db.QueryContext(ctx, listarFotosPorVivienda, viviendaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Foto
	for rows.Next() {
		var i Foto
		if err := rows.Scan(&i.FotoID, &i.Url, &i.ViviendaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMenuDiarios = `-- name: ListarMenuDiarios :many

SELECT id, fecha, alimentacion_id FROM menu_diario
`

// MENU DIARIO --
func (q *Queries) ListarMenuDiarios(ctx context.Context) ([]MenuDiario, error) {
	rows, err := q.db.QueryContext(ctx, listarMenuDiarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuDiario
	for rows.Next() {
		var i MenuDiario
		if err := rows.Scan(&i.ID, &i.Fecha, &i.AlimentacionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMenuDiariosPorAlimentacion = `-- name: ListarMenuDiariosPorAlimentacion :many
SELECT id, fecha, alimentacion_id FROM menu_diario
WHERE alimentacion_id = ?
`

func (q *Queries) ListarMenuDiariosPorAlimentacion(ctx context.Context, alimentacionID int64) ([]MenuDiario, error) {
	rows, err := q.db.QueryContext(ctx, listarMenuDiariosPorAlimentacion, alimentacionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuDiario
	for rows.Next() {
		var i MenuDiario
		if err := rows.Scan(&i.ID, &i.Fecha, &i.AlimentacionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPlatos = `-- name: ListarPlatos :many

SELECT id, nombre_plato, descripcion, categoria, precio, menu_diario_id FROM plato
`

// PLATOS --
func (q *Queries) ListarPlatos(ctx context.Context) ([]Plato, error) {
	rows, err := q.db.QueryContext(ctx, listarPlatos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plato
	for rows.Next() {
		var i Plato
		if err := rows.Scan(
			&i.ID,
			&i.NombrePlato,
			&i.Descripcion,
			&i.Categoria,
			&i.Precio,
			&i.MenuDiarioID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPlatosPorMenuDiario = `-- name: ListarPlatosPorMenuDiario :many
SELECT id, nombre_plato, descripcion, categoria, precio, menu_diario_id FROM plato
WHERE menu_diario_id = ?
`

func (q *Queries) ListarPlatosPorMenuDiario(ctx context.Context, menuDiarioID int64) ([]Plato, error) {
	rows, err := q.db.QueryContext(ctx, listarPlatosPorMenuDiario, menuDiarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plato
	for rows.Next() {
		var i Plato
		if err := rows.Scan(
			&i.ID,
			&i.NombrePlato,
			&i.Descripcion,
			&i.Categoria,
			&i.Precio,
			&i.MenuDiarioID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarResenas = `-- name: ListarResenas :many

SELECT id, comentario, calificacion, alimentacion_id FROM resena
`

// RESENAS --
func (q *Queries) ListarResenas(ctx context.Context) ([]Resena, error) {
	rows, err := q.db.QueryContext(ctx, listarResenas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resena
	for rows.Next() {
		var i Resena
		if err := rows.Scan(
			&i.ID,
			&i.Comentario,
			&i.Calificacion,
			&i.AlimentacionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarResenasPorAlimentacion = `-- name: ListarResenasPorAlimentacion :many
SELECT id, comentario, calificacion, alimentacion_id FROM resena
WHERE alimentacion_id = ?
`

func (q *Queries) ListarResenasPorAlimentacion(ctx context.Context, alimentacionID int64) ([]Resena, error) {
	rows, err := q.db.QueryContext(ctx, listarResenasPorAlimentacion, alimentacionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resena
	for rows.Next() {
		var i Resena
		if err := rows.Scan(
			&i.ID,
			&i.Comentario,
			&i.Calificacion,
			&i.AlimentacionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarRutas = `-- name: ListarRutas :many

SELECT id, nombre_linea, frecuencia_aprox, precio, descripcion_ruta, cooperativa_id, sector_origen_id, sector_destino_id, provider_id FROM ruta_transporte
`

// RUTAS DE TRANSPORTE --
func (q *Queries) ListarRutas(ctx context.Context) ([]RutaTransporte, error) {
	rows, err := q.db.QueryContext(ctx, listarRutas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RutaTransporte
	for rows.Next() {
		var i RutaTransporte
		if err := rows.Scan(
			&i.ID,
			&i.NombreLinea,
			&i.FrecuenciaAprox,
			&i.Precio,
			&i.DescripcionRuta,
			&i.CooperativaID,
			&i.SectorOrigenID,
			&i.SectorDestinoID,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarViviendas = `-- name: ListarViviendas :many

SELECT vivienda_id, titulo, tipo_vivienda, precio, garantia, precio_garantia, direccion, luz, agua, amueblado, internet, bano_privado, numero_habitaciones, mascotas, genero_preferido, reglas_convivencia, telefono, email, estado, comentario, sector_id, proveedor_id FROM vivienda
`

// VIVIENDAS --
func (q *Queries) ListarViviendas(ctx context.Context) ([]Vivienda, error) {
	rows, err := q.db.QueryContext(ctx, listarViviendas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vivienda
	for rows.Next() {
		var i Vivienda
		if err := rows.Scan(
			&i.ViviendaID,
			&i.Titulo,
			&i.TipoVivienda,
			&i.Precio,
			&i.Garantia,
			&i.PrecioGarantia,
			&i.Direccion,
			&i.Luz,
			&i.Agua,
			&i.Amueblado,
			&i.Internet,
			&i.BanoPrivado,
			&i.NumeroHabitaciones,
			&i.Mascotas,
			&i.GeneroPreferido,
			&i.ReglasConvivencia,
			&i.Telefono,
			&i.Email,
			&i.Estado,
			&i.Comentario,
			&i.SectorID,
			&i.ProveedorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerAlimentacion = `-- name: ObtenerAlimentacion :one
SELECT id, nombre_local, descripcion, ubicacion, direccion, horario_apertura, horario_cierre, telefono, tipo_comida, precio_promedio, provider_id FROM alimentacion
WHERE id = ?
`

func (q *Queries) ObtenerAlimentacion(ctx context.Context, id int64) (Alimentacion, error) {
	row := q.db.QueryRowContext(ctx, obtenerAlimentacion, id)
	var i Alimentacion
	err := row.Scan(
		&i.ID,
		&i.NombreLocal,
		&i.Descripcion,
		&i.Ubicacion,
		&i.Direccion,
		&i.HorarioApertura,
		&i.HorarioCierre,
		&i.Telefono,
		&i.TipoComida,
		&i.PrecioPromedio,
		&i.ProviderID,
	)
	return i, err
}

const obtenerAplicarVivienda = `-- name: ObtenerAplicarVivienda :one
SELECT aplicar_vivienda_id, estudiante_id, vivienda_id, estado FROM aplicar_vivienda
WHERE aplicar_vivienda_id = ?
`

func (q *Queries) ObtenerAplicarVivienda(ctx context.Context, aplicarViviendaID int64) (AplicarVivienda, error) {
	row := q.db.QueryRowContext(ctx, obtenerAplicarVivienda, aplicarViviendaID)
	var i AplicarVivienda
	err := row.Scan(
		&i.AplicarViviendaID,
		&i.EstudianteID,
		&i.ViviendaID,
		&i.Estado,
	)
	return i, err
}

const obtenerCooperativa = `-- name: ObtenerCooperativa :one
SELECT id, nombre, telefono, descripcion FROM cooperativa
WHERE id = ?
`

func (q *Queries) ObtenerCooperativa(ctx context.Context, id int64) (Cooperativa, error) {
	row := q.db.QueryRowContext(ctx, obtenerCooperativa, id)
	var i Cooperativa
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Telefono,
		&i.Descripcion,
	)
	return i, err
}

const obtenerFoto = `-- name: ObtenerFoto :one
SELECT foto_id, url, vivienda_id FROM foto
WHERE foto_id = ?
`

func (q *Queries) ObtenerFoto(ctx context.Context, fotoID int64) (Foto, error) {
	row := q.db.QueryRowContext(ctx, obtenerFoto, fotoID)
	var i Foto
	err := row.Scan(&i.FotoID, &i.Url, &i.ViviendaID)
	return i, err
}

const obtenerMenuDiario = `-- name: ObtenerMenuDiario :one
SELECT id, fecha, alimentacion_id FROM menu_diario
WHERE id = ?
`

func (q *Queries) ObtenerMenuDiario(ctx context.Context, id int64) (MenuDiario, error) {
	row := q.db.QueryRowContext(ctx, obtenerMenuDiario, id)
	var i MenuDiario
	err := row.Scan(&i.ID, &i.Fecha, &i.AlimentacionID)
	return i, err
}

const obtenerPlato = `-- name: ObtenerPlato :one
SELECT id, nombre_plato, descripcion, categoria, precio, menu_diario_id FROM plato
WHERE id = ?
`

func (q *Queries) ObtenerPlato(ctx context.Context, id int64) (Plato, error) {
	row := q.db.QueryRowContext(ctx, obtenerPlato, id)
	var i Plato
	err := row.Scan(
		&i.ID,
		&i.NombrePlato,
		&i.Descripcion,
		&i.Categoria,
		&i.Precio,
		&i.MenuDiarioID,
	)
	return i, err
}

const obtenerResena = `-- name: ObtenerResena :one
SELECT id, comentario, calificacion, alimentacion_id FROM resena
WHERE id = ?
`

func (q *Queries) ObtenerResena(ctx context.Context, id int64) (Resena, error) {
	row := q.db.QueryRowContext(ctx, obtenerResena, id)
	var i Resena
	err := row.Scan(
		&i.ID,
		&i.Comentario,
		&i.Calificacion,
		&i.AlimentacionID,
	)
	return i, err
}

const obtenerRuta = `-- name: ObtenerRuta :one
SELECT id, nombre_linea, frecuencia_aprox, precio, descripcion_ruta, cooperativa_id, sector_origen_id, sector_destino_id, provider_id FROM ruta_transporte
WHERE id = ?
`

func (q *Queries) ObtenerRuta(ctx context.Context, id int64) (RutaTransporte, error) {
	row := q.db.QueryRowContext(ctx, obtenerRuta, id)
	var i RutaTransporte
	err := row.Scan(
		&i.ID,
		&i.NombreLinea,
		&i.FrecuenciaAprox,
		&i.Precio,
		&i.DescripcionRuta,
		&i.CooperativaID,
		&i.SectorOrigenID,
		&i.SectorDestinoID,
		&i.ProviderID,
	)
	return i, err
}

const obtenerVivienda = `-- name: ObtenerVivienda :one
SELECT vivienda_id, titulo, tipo_vivienda, precio, garantia, precio_garantia, direccion, luz, agua, amueblado, internet, bano_privado, numero_habitaciones, mascotas, genero_preferido, reglas_convivencia, telefono, email, estado, comentario, sector_id, proveedor_id FROM vivienda
WHERE vivienda_id = ?
`

func (q *Queries) ObtenerVivienda(ctx context.Context, viviendaID int64) (Vivienda, error) {
	row := q.db.QueryRowContext(ctx, obtenerVivienda, viviendaID)
	var i Vivienda
	err := row.Scan(
		&i.ViviendaID,
		&i.Titulo,
		&i.TipoVivienda,
		&i.Precio,
		&i.Garantia,
		&i.PrecioGarantia,
		&i.Direccion,
		&i.Luz,
		&i.Agua,
		&i.Amueblado,
		&i.Internet,
		&i.BanoPrivado,
		&i.NumeroHabitaciones,
		&i.Mascotas,
		&i.GeneroPreferido,
		&i.ReglasConvivencia,
		&i.Telefono,
		&i.Email,
		&i.Estado,
		&i.Comentario,
		&i.SectorID,
		&i.ProveedorID,
	)
	return i, err
}
