// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const actualizarAlimentacion = `-- name: ActualizarAlimentacion :one
UPDATE alimentacion
SET nombre_local = ?, descripcion = ?, ubicacion = ?, direccion = ?,
    horario_apertura = ?, horario_cierre = ?, telefono = ?,
    tipo_comida = ?, precio_promedio = ?, provider_id = ?
WHERE id = ?
RETURNING id, nombre_local, descripcion, ubicacion, direccion, horario_apertura, horario_cierre, telefono, tipo_comida, precio_promedio, provider_id
`

type ActualizarAlimentacionParams struct {
	NombreLocal     string
	Descripcion     string
	Ubicacion       string
	Direccion       string
	HorarioApertura string
	HorarioCierre   string
	Telefono        string
	TipoComida      string
	PrecioPromedio  float64
	ProviderID      int64
	ID              int64
}

func (q *Queries) ActualizarAlimentacion(ctx context.Context, arg ActualizarAlimentacionParams) (Alimentacion, error) {
	row := q.db.QueryRowContext(ctx, actualizarAlimentacion,
		arg.NombreLocal,
		arg.Descripcion,
		arg.Ubicacion,
		arg.Direccion,
		arg.HorarioApertura,
		arg.HorarioCierre,
		arg.Telefono,
		arg.TipoComida,
		arg.PrecioPromedio,
		arg.ProviderID,
		arg.ID,
	)
	var i Alimentacion
	err := row.Scan(
		&i.ID,
		&i.NombreLocal,
		&i.Descripcion,
		&i.Ubicacion,
		&i.Direccion,
		&i.HorarioApertura,
		&i.HorarioCierre,
		&i.Telefono,
		&i.TipoComida,
		&i.PrecioPromedio,
		&i.ProviderID,
	)
	return i, err
}

const actualizarAplicarVivienda = `-- name: ActualizarAplicarVivienda :one
UPDATE aplicar_vivienda
SET estudiante_id = ?, vivienda_id = ?, estado = ?
WHERE aplicar_vivienda_id = ?
RETURNING aplicar_vivienda_id, estudiante_id, vivienda_id, estado
`

type ActualizarAplicarViviendaParams struct {
	EstudianteID      int64
	ViviendaID        int64
	Estado            string
	AplicarViviendaID int64
}

func (q *Queries) ActualizarAplicarVivienda(ctx context.Context, arg ActualizarAplicarViviendaParams) (AplicarVivienda, error) {
	row := q.db.QueryRowContext(ctx, actualizarAplicarVivienda,
		arg.EstudianteID,
		arg.ViviendaID,
		arg.Estado,
		arg.AplicarViviendaID,
	)
	var i AplicarVivienda
	err := row.Scan(
		&i.AplicarViviendaID,
		&i.EstudianteID,
		&i.ViviendaID,
		&i.Estado,
	)
	return i, err
}

const actualizarCooperativa = `-- name: ActualizarCooperativa :one
UPDATE cooperativa
SET nombre = ?, telefono = ?, descripcion = ?
WHERE id = ?
RETURNING id, nombre, telefono, descripcion
`

type ActualizarCooperativaParams struct {
	Nombre      string
	Telefono    string
	Descripcion string
	ID          int64
}

func (q *Queries) ActualizarCooperativa(ctx context.Context, arg ActualizarCooperativaParams) (Cooperativa, error) {
	row := q.db.QueryRowContext(ctx, actualizarCooperativa,
		arg.Nombre,
		arg.Telefono,
		arg.Descripcion,
		arg.ID,
	)
	var i Cooperativa
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Telefono,
		&i.Descripcion,
	)
	return i, err
}

const actualizarFoto = `-- name: ActualizarFoto :one
UPDATE foto
SET url = ?, vivienda_id = ?
WHERE foto_id = ?
RETURNING foto_id, url, vivienda_id
`

type ActualizarFotoParams struct {
	Url        string
	ViviendaID int64
	FotoID     int64
}

func (q *Queries) ActualizarFoto(ctx context.Context, arg ActualizarFotoParams) (Foto, error) {
	row := q.db.QueryRowContext(ctx, actualizarFoto, arg.Url, arg.ViviendaID, arg.FotoID)
	var i Foto
	err := row.Scan(&i.FotoID, &i.Url, &i.ViviendaID)
	return i, err
}

const actualizarMenuDiario = `-- name: ActualizarMenuDiario :one
UPDATE menu_diario
SET fecha = ?, alimentacion_id = ?
WHERE id = ?
RETURNING id, fecha, alimentacion_id
`

type ActualizarMenuDiarioParams struct {
	Fecha          string
	AlimentacionID int64
	ID             int64
}

func (q *Queries) ActualizarMenuDiario(ctx context.Context, arg ActualizarMenuDiarioParams) (MenuDiario, error) {
	row := q.db.QueryRowContext(ctx, actualizarMenuDiario, arg.Fecha, arg.AlimentacionID, arg.ID)
	var i MenuDiario
	err := row.Scan(&i.ID, &i.Fecha, &i.AlimentacionID)
	return i, err
}

const actualizarParada = `-- name: ActualizarParada :one
UPDATE paradas_bus
SET nombre_parada = ?, direccion = ?, descripcion = ?
WHERE id = ?
RETURNING id, nombre_parada, direccion, descripcion
`

type ActualizarParadaParams struct {
	NombreParada string
	Direccion    string
	Descripcion  string
	ID           int64
}

func (q *Queries) ActualizarParada(ctx context.Context, arg ActualizarParadaParams) (ParadasBus, error) {
	row := q.db.QueryRowContext(ctx, actualizarParada,
		arg.NombreParada,
		arg.Direccion,
		arg.Descripcion,
		arg.ID,
	)
	var i ParadasBus
	err := row.Scan(
		&i.ID,
		&i.NombreParada,
		&i.Direccion,
		&i.Descripcion,
	)
	return i, err
}

const actualizarPlato = `-- name: ActualizarPlato :one
UPDATE plato
SET nombre_plato = ?, descripcion = ?, categoria = ?,
    precio = ?, menu_diario_id = ?
WHERE id = ?
RETURNING id, nombre_plato, descripcion, categoria, precio, menu_diario_id
`

type ActualizarPlatoParams struct {
	NombrePlato  string
	Descripcion  string
	Categoria    string
	Precio       float64
	MenuDiarioID int64
	ID           int64
}

func (q *Queries) ActualizarPlato(ctx context.Context, arg ActualizarPlatoParams) (Plato, error) {
	row := q.db.QueryRowContext(ctx, actualizarPlato,
		arg.NombrePlato,
		arg.Descripcion,
		arg.Categoria,
		arg.Precio,
		arg.MenuDiarioID,
		arg.ID,
	)
	var i Plato
	err := row.Scan(
		&i.ID,
		&i.NombrePlato,
		&i.Descripcion,
		&i.Categoria,
		&i.Precio,
		&i.MenuDiarioID,
	)
	return i, err
}

const actualizarResena = `-- name: ActualizarResena :one
UPDATE resena
SET comentario = ?, calificacion = ?, alimentacion_id = ?
WHERE id = ?
RETURNING id, comentario, calificacion, alimentacion_id
`

type ActualizarResenaParams struct {
	Comentario     string
	Calificacion   int64
	AlimentacionID int64
	ID             int64
}

func (q *Queries) ActualizarResena(ctx context.Context, arg ActualizarResenaParams) (Resena, error) {
	row := q.db.QueryRowContext(ctx, actualizarResena,
		arg.Comentario,
		arg.Calificacion,
		arg.AlimentacionID,
		arg.ID,
	)
	var i Resena
	err := row.Scan(
		&i.ID,
		&i.Comentario,
		&i.Calificacion,
		&i.AlimentacionID,
	)
	return i, err
}

const actualizarRuta = `-- name: ActualizarRuta :one
UPDATE ruta_transporte
SET nombre_linea = ?, frecuencia_aprox = ?, precio = ?,
    descripcion_ruta = ?, cooperativa_id = ?,
    sector_origen_id = ?, sector_destino_id = ?, parada_bus_id = ?  
WHERE id = ?
RETURNING id, nombre_linea, frecuencia_aprox, precio, descripcion_ruta, cooperativa_id, sector_origen_id, sector_destino_id, parada_bus_id
`

type ActualizarRutaParams struct {
	NombreLinea     string
	FrecuenciaAprox string
	Precio          float64
	DescripcionRuta string
	CooperativaID   int64
	SectorOrigenID  int64
	SectorDestinoID int64
	ParadaBusID     int64
	ID              int64
}

func (q *Queries) ActualizarRuta(ctx context.Context, arg ActualizarRutaParams) (RutaTransporte, error) {
	row := q.db.QueryRowContext(ctx, actualizarRuta,
		arg.NombreLinea,
		arg.FrecuenciaAprox,
		arg.Precio,
		arg.DescripcionRuta,
		arg.CooperativaID,
		arg.SectorOrigenID,
		arg.SectorDestinoID,
		arg.ParadaBusID,
		arg.ID,
	)
	var i RutaTransporte
	err := row.Scan(
		&i.ID,
		&i.NombreLinea,
		&i.FrecuenciaAprox,
		&i.Precio,
		&i.DescripcionRuta,
		&i.CooperativaID,
		&i.SectorOrigenID,
		&i.SectorDestinoID,
		&i.ParadaBusID,
	)
	return i, err
}

const actualizarSector = `-- name: ActualizarSector :one
UPDATE sector
SET nombre = ?
WHERE sector_id = ?
RETURNING sector_id, nombre
`

type ActualizarSectorParams struct {
	Nombre   string
	SectorID int64
}

func (q *Queries) ActualizarSector(ctx context.Context, arg ActualizarSectorParams) (Sector, error) {
	row := q.db.QueryRowContext(ctx, actualizarSector, arg.Nombre, arg.SectorID)
	var i Sector
	err := row.Scan(&i.SectorID, &i.Nombre)
	return i, err
}

const actualizarVivienda = `-- name: ActualizarVivienda :one
UPDATE vivienda
SET titulo = ?, tipo_vivienda = ?, precio = ?, garantia = ?,
    precio_garantia = ?, direccion = ?, luz = ?, agua = ?,
    amueblado = ?, internet = ?, bano_privado = ?,
    numero_habitaciones = ?, mascotas = ?, genero_preferido = ?,
    reglas_convivencia = ?, telefono = ?, email = ?,
    estado = ?, comentario = ?, sector_id = ?, proveedor_id = ?
WHERE vivienda_id = ?
RETURNING vivienda_id, titulo, tipo_vivienda, precio, garantia, precio_garantia, direccion, luz, agua, amueblado, internet, bano_privado, numero_habitaciones, mascotas, genero_preferido, reglas_convivencia, telefono, email, estado, comentario, sector_id, proveedor_id
`

type ActualizarViviendaParams struct {
	Titulo             string
	TipoVivienda       string
	Precio             float64
	Garantia           bool
	PrecioGarantia     float64
	Direccion          string
	Luz                bool
	Agua               bool
	Amueblado          bool
	Internet           bool
	BanoPrivado        bool
	NumeroHabitaciones int64
	Mascotas           bool
	GeneroPreferido    string
	ReglasConvivencia  string
	Telefono           string
	Email              string
	Estado             string
	Comentario         string
	SectorID           int64
	ProveedorID        int64
	ViviendaID         int64
}

func (q *Queries) ActualizarVivienda(ctx context.Context, arg ActualizarViviendaParams) (Vivienda, error) {
	row := q.db.QueryRowContext(ctx, actualizarVivienda,
		arg.Titulo,
		arg.TipoVivienda,
		arg.Precio,
		arg.Garantia,
		arg.PrecioGarantia,
		arg.Direccion,
		arg.Luz,
		arg.Agua,
		arg.Amueblado,
		arg.Internet,
		arg.BanoPrivado,
		arg.NumeroHabitaciones,
		arg.Mascotas,
		arg.GeneroPreferido,
		arg.ReglasConvivencia,
		arg.Telefono,
		arg.Email,
		arg.Estado,
		arg.Comentario,
		arg.SectorID,
		arg.ProveedorID,
		arg.ViviendaID,
	)
	var i Vivienda
	err := row.Scan(
		&i.ViviendaID,
		&i.Titulo,
		&i.TipoVivienda,
		&i.Precio,
		&i.Garantia,
		&i.PrecioGarantia,
		&i.Direccion,
		&i.Luz,
		&i.Agua,
		&i.Amueblado,
		&i.Internet,
		&i.BanoPrivado,
		&i.NumeroHabitaciones,
		&i.Mascotas,
		&i.GeneroPreferido,
		&i.ReglasConvivencia,
		&i.Telefono,
		&i.Email,
		&i.Estado,
		&i.Comentario,
		&i.SectorID,
		&i.ProveedorID,
	)
	return i, err
}

const borrarAlimentacion = `-- name: BorrarAlimentacion :execrows
DELETE FROM alimentacion WHERE id = ?
`

func (q *Queries) BorrarAlimentacion(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarAlimentacion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarAplicarVivienda = `-- name: BorrarAplicarVivienda :execrows
DELETE FROM aplicar_vivienda WHERE aplicar_vivienda_id = ?
`

func (q *Queries) BorrarAplicarVivienda(ctx context.Context, aplicarViviendaID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarAplicarVivienda, aplicarViviendaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarCooperativa = `-- name: BorrarCooperativa :execrows
DELETE FROM cooperativa WHERE id = ?
`

func (q *Queries) BorrarCooperativa(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarCooperativa, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarFoto = `-- name: BorrarFoto :execrows
DELETE FROM foto WHERE foto_id = ?
`

func (q *Queries) BorrarFoto(ctx context.Context, fotoID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarFoto, fotoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarMenuDiario = `-- name: BorrarMenuDiario :execrows
DELETE FROM menu_diario WHERE id = ?
`

func (q *Queries) BorrarMenuDiario(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarMenuDiario, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarParada = `-- name: BorrarParada :execrows
DELETE FROM paradas_bus WHERE id = ?
`

func (q *Queries) BorrarParada(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarParada, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarPlato = `-- name: BorrarPlato :execrows
DELETE FROM plato WHERE id = ?
`

func (q *Queries) BorrarPlato(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarPlato, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarResena = `-- name: BorrarResena :execrows
DELETE FROM resena WHERE id = ?
`

func (q *Queries) BorrarResena(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarResena, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarRuta = `-- name: BorrarRuta :execrows
DELETE FROM ruta_transporte WHERE id = ?
`

func (q *Queries) BorrarRuta(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarRuta, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarSector = `-- name: BorrarSector :execrows
DELETE FROM sector WHERE sector_id = ?
`

func (q *Queries) BorrarSector(ctx context.Context, sectorID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarSector, sectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarAlimentacionPorID = `-- name: BuscarAlimentacionPorID :one
SELECT id, nombre_local, descripcion, ubicacion, direccion, horario_apertura, horario_cierre, telefono, tipo_comida, precio_promedio, provider_id FROM alimentacion
WHERE id = ?
`

func (q *Queries) BuscarAlimentacionPorID(ctx context.Context, id int64) (Alimentacion, error) {
	row := q.db.QueryRowContext(ctx, buscarAlimentacionPorID, id)
	var i Alimentacion
	err := row.Scan(
		&i.ID,
		&i.NombreLocal,
		&i.Descripcion,
		&i.Ubicacion,
		&i.Direccion,
		&i.HorarioApertura,
		&i.HorarioCierre,
		&i.Telefono,
		&i.TipoComida,
		&i.PrecioPromedio,
		&i.ProviderID,
	)
	return i, err
}

const buscarAplicarViviendaPorID = `-- name: BuscarAplicarViviendaPorID :one
SELECT aplicar_vivienda_id, estudiante_id, vivienda_id, estado FROM aplicar_vivienda
WHERE aplicar_vivienda_id = ?
`

func (q *Queries) BuscarAplicarViviendaPorID(ctx context.Context, aplicarViviendaID int64) (AplicarVivienda, error) {
	row := q.db.QueryRowContext(ctx, buscarAplicarViviendaPorID, aplicarViviendaID)
	var i AplicarVivienda
	err := row.Scan(
		&i.AplicarViviendaID,
		&i.EstudianteID,
		&i.ViviendaID,
		&i.Estado,
	)
	return i, err
}

const buscarCooperativaPorID = `-- name: BuscarCooperativaPorID :one
SELECT id, nombre, telefono, descripcion FROM cooperativa
WHERE id = ?
`

func (q *Queries) BuscarCooperativaPorID(ctx context.Context, id int64) (Cooperativa, error) {
	row := q.db.QueryRowContext(ctx, buscarCooperativaPorID, id)
	var i Cooperativa
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Telefono,
		&i.Descripcion,
	)
	return i, err
}

const buscarFotoPorID = `-- name: BuscarFotoPorID :one
SELECT foto_id, url, vivienda_id FROM foto
WHERE foto_id = ?
`

func (q *Queries) BuscarFotoPorID(ctx context.Context, fotoID int64) (Foto, error) {
	row := q.db.QueryRowContext(ctx, buscarFotoPorID, fotoID)
	var i Foto
	err := row.Scan(&i.FotoID, &i.Url, &i.ViviendaID)
	return i, err
}

const buscarMenuDiarioPorID = `-- name: BuscarMenuDiarioPorID :one
SELECT id, fecha, alimentacion_id FROM menu_diario
WHERE id = ?
`

func (q *Queries) BuscarMenuDiarioPorID(ctx context.Context, id int64) (MenuDiario, error) {
	row := q.db.QueryRowContext(ctx, buscarMenuDiarioPorID, id)
	var i MenuDiario
	err := row.Scan(&i.ID, &i.Fecha, &i.AlimentacionID)
	return i, err
}

const buscarParadaPorID = `-- name: BuscarParadaPorID :one
SELECT id, nombre_parada, direccion, descripcion FROM paradas_bus
WHERE id = ?
`

func (q *Queries) BuscarParadaPorID(ctx context.Context, id int64) (ParadasBus, error) {
	row := q.db.QueryRowContext(ctx, buscarParadaPorID, id)
	var i ParadasBus
	err := row.Scan(
		&i.ID,
		&i.NombreParada,
		&i.Direccion,
		&i.Descripcion,
	)
	return i, err
}

const buscarPlatoPorID = `-- name: BuscarPlatoPorID :one
SELECT id, nombre_plato, descripcion, categoria, precio, menu_diario_id FROM plato
WHERE id = ?
`

func (q *Queries) BuscarPlatoPorID(ctx context.Context, id int64) (Plato, error) {
	row := q.db.QueryRowContext(ctx, buscarPlatoPorID, id)
	var i Plato
	err := row.Scan(
		&i.ID,
		&i.NombrePlato,
		&i.Descripcion,
		&i.Categoria,
		&i.Precio,
		&i.MenuDiarioID,
	)
	return i, err
}

const buscarResenaPorID = `-- name: BuscarResenaPorID :one
SELECT id, comentario, calificacion, alimentacion_id FROM resena
WHERE id = ?
`

func (q *Queries) BuscarResenaPorID(ctx context.Context, id int64) (Resena, error) {
	row := q.db.QueryRowContext(ctx, buscarResenaPorID, id)
	var i Resena
	err := row.Scan(
		&i.ID,
		&i.Comentario,
		&i.Calificacion,
		&i.AlimentacionID,
	)
	return i, err
}

const buscarRutaPorID = `-- name: BuscarRutaPorID :one
SELECT id, nombre_linea, frecuencia_aprox, precio, descripcion_ruta, cooperativa_id, sector_origen_id, sector_destino_id, parada_bus_id FROM ruta_transporte
WHERE id = ?
`

func (q *Queries) BuscarRutaPorID(ctx context.Context, id int64) (RutaTransporte, error) {
	row := q.db.QueryRowContext(ctx, buscarRutaPorID, id)
	var i RutaTransporte
	err := row.Scan(
		&i.ID,
		&i.NombreLinea,
		&i.FrecuenciaAprox,
		&i.Precio,
		&i.DescripcionRuta,
		&i.CooperativaID,
		&i.SectorOrigenID,
		&i.SectorDestinoID,
		&i.ParadaBusID,
	)
	return i, err
}

const buscarSectorPorID = `-- name: BuscarSectorPorID :one
SELECT sector_id, nombre FROM sector
WHERE sector_id = ?
`

func (q *Queries) BuscarSectorPorID(ctx context.Context, sectorID int64) (Sector, error) {
	row := q.db.QueryRowContext(ctx, buscarSectorPorID, sectorID)
	var i Sector
	err := row.Scan(&i.SectorID, &i.Nombre)
	return i, err
}

const buscarViviendaPorID = `-- name: BuscarViviendaPorID :one
SELECT vivienda_id, titulo, tipo_vivienda, precio, garantia, precio_garantia, direccion, luz, agua, amueblado, internet, bano_privado, numero_habitaciones, mascotas, genero_preferido, reglas_convivencia, telefono, email, estado, comentario, sector_id, proveedor_id FROM vivienda
WHERE vivienda_id = ?
`

func (q *Queries) BuscarViviendaPorID(ctx context.Context, viviendaID int64) (Vivienda, error) {
	row := q.db.QueryRowContext(ctx, buscarViviendaPorID, viviendaID)
	var i Vivienda
	err := row.Scan(
		&i.ViviendaID,
		&i.Titulo,
		&i.TipoVivienda,
		&i.Precio,
		&i.Garantia,
		&i.PrecioGarantia,
		&i.Direccion,
		&i.Luz,
		&i.Agua,
		&i.Amueblado,
		&i.Internet,
		&i.BanoPrivado,
		&i.NumeroHabitaciones,
		&i.Mascotas,
		&i.GeneroPreferido,
		&i.ReglasConvivencia,
		&i.Telefono,
		&i.Email,
		&i.Estado,
		&i.Comentario,
		&i.SectorID,
		&i.ProveedorID,
	)
	return i, err
}

const crearAlimentacion = `-- name: CrearAlimentacion :one
INSERT INTO alimentacion (nombre_local, descripcion, ubicacion, direccion, horario_apertura, horario_cierre, telefono, tipo_comida, precio_promedio, provider_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, nombre_local, descripcion, ubicacion, direccion, horario_apertura, horario_cierre, telefono, tipo_comida, precio_promedio, provider_id
`

type CrearAlimentacionParams struct {
	NombreLocal     string
	Descripcion     string
	Ubicacion       string
	Direccion       string
	HorarioApertura string
	HorarioCierre   string
	Telefono        string
	TipoComida      string
	PrecioPromedio  float64
	ProviderID      int64
}

func (q *Queries) CrearAlimentacion(ctx context.Context, arg CrearAlimentacionParams) (Alimentacion, error) {
	row := q.db.QueryRowContext(ctx, crearAlimentacion,
		arg.NombreLocal,
		arg.Descripcion,
		arg.Ubicacion,
		arg.Direccion,
		arg.HorarioApertura,
		arg.HorarioCierre,
		arg.Telefono,
		arg.TipoComida,
		arg.PrecioPromedio,
		arg.ProviderID,
	)
	var i Alimentacion
	err := row.Scan(
		&i.ID,
		&i.NombreLocal,
		&i.Descripcion,
		&i.Ubicacion,
		&i.Direccion,
		&i.HorarioApertura,
		&i.HorarioCierre,
		&i.Telefono,
		&i.TipoComida,
		&i.PrecioPromedio,
		&i.ProviderID,
	)
	return i, err
}

const crearAplicarVivienda = `-- name: CrearAplicarVivienda :one
INSERT INTO aplicar_vivienda (estudiante_id, vivienda_id, estado)
VALUES (?, ?, ?)
RETURNING aplicar_vivienda_id, estudiante_id, vivienda_id, estado
`

type CrearAplicarViviendaParams struct {
	EstudianteID int64
	ViviendaID   int64
	Estado       string
}

func (q *Queries) CrearAplicarVivienda(ctx context.Context, arg CrearAplicarViviendaParams) (AplicarVivienda, error) {
	row := q.db.QueryRowContext(ctx, crearAplicarVivienda, arg.EstudianteID, arg.ViviendaID, arg.Estado)
	var i AplicarVivienda
	err := row.Scan(
		&i.AplicarViviendaID,
		&i.EstudianteID,
		&i.ViviendaID,
		&i.Estado,
	)
	return i, err
}

const crearCooperativa = `-- name: CrearCooperativa :one
INSERT INTO cooperativa (nombre, telefono, descripcion)
VALUES (?, ?, ?)
RETURNING id, nombre, telefono, descripcion
`

type CrearCooperativaParams struct {
	Nombre      string
	Telefono    string
	Descripcion string
}

func (q *Queries) CrearCooperativa(ctx context.Context, arg CrearCooperativaParams) (Cooperativa, error) {
	row := q.db.QueryRowContext(ctx, crearCooperativa, arg.Nombre, arg.Telefono, arg.Descripcion)
	var i Cooperativa
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Telefono,
		&i.Descripcion,
	)
	return i, err
}

const crearFoto = `-- name: CrearFoto :one
INSERT INTO foto (url, vivienda_id)
VALUES (?, ?)
RETURNING foto_id, url, vivienda_id
`

type CrearFotoParams struct {
	Url        string
	ViviendaID int64
}

func (q *Queries) CrearFoto(ctx context.Context, arg CrearFotoParams) (Foto, error) {
	row := q.db.QueryRowContext(ctx, crearFoto, arg.Url, arg.ViviendaID)
	var i Foto
	err := row.Scan(&i.FotoID, &i.Url, &i.ViviendaID)
	return i, err
}

const crearMenuDiario = `-- name: CrearMenuDiario :one
INSERT INTO menu_diario (fecha, alimentacion_id)
VALUES (?, ?)
RETURNING id, fecha, alimentacion_id
`

type CrearMenuDiarioParams struct {
	Fecha          string
	AlimentacionID int64
}

func (q *Queries) CrearMenuDiario(ctx context.Context, arg CrearMenuDiarioParams) (MenuDiario, error) {
	row := q.db.QueryRowContext(ctx, crearMenuDiario, arg.Fecha, arg.AlimentacionID)
	var i MenuDiario
	err := row.Scan(&i.ID, &i.Fecha, &i.AlimentacionID)
	return i, err
}

const crearParada = `-- name: CrearParada :one
INSERT INTO paradas_bus (nombre_parada, direccion, descripcion)
VALUES (?, ?, ?)
RETURNING id, nombre_parada, direccion, descripcion
`

type CrearParadaParams struct {
	NombreParada string
	Direccion    string
	Descripcion  string
}

func (q *Queries) CrearParada(ctx context.Context, arg CrearParadaParams) (ParadasBus, error) {
	row := q.db.QueryRowContext(ctx, crearParada, arg.NombreParada, arg.Direccion, arg.Descripcion)
	var i ParadasBus
	err := row.Scan(
		&i.ID,
		&i.NombreParada,
		&i.Direccion,
		&i.Descripcion,
	)
	return i, err
}

const crearPlato = `-- name: CrearPlato :one
INSERT INTO plato (nombre_plato, descripcion, categoria, precio, menu_diario_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id, nombre_plato, descripcion, categoria, precio, menu_diario_id
`

type CrearPlatoParams struct {
	NombrePlato  string
	Descripcion  string
	Categoria    string
	Precio       float64
	MenuDiarioID int64
}

func (q *Queries) CrearPlato(ctx context.Context, arg CrearPlatoParams) (Plato, error) {
	row := q.db.QueryRowContext(ctx, crearPlato,
		arg.NombrePlato,
		arg.Descripcion,
		arg.Categoria,
		arg.Precio,
		arg.MenuDiarioID,
	)
	var i Plato
	err := row.Scan(
		&i.ID,
		&i.NombrePlato,
		&i.Descripcion,
		&i.Categoria,
		&i.Precio,
		&i.MenuDiarioID,
	)
	return i, err
}

const crearResena = `-- name: CrearResena :one
INSERT INTO resena (comentario, calificacion, alimentacion_id)
VALUES (?, ?, ?)
RETURNING id, comentario, calificacion, alimentacion_id
`

type CrearResenaParams struct {
	Comentario     string
	Calificacion   int64
	AlimentacionID int64
}

func (q *Queries) CrearResena(ctx context.Context, arg CrearResenaParams) (Resena, error) {
	row := q.db.QueryRowContext(ctx, crearResena, arg.Comentario, arg.Calificacion, arg.AlimentacionID)
	var i Resena
	err := row.Scan(
		&i.ID,
		&i.Comentario,
		&i.Calificacion,
		&i.AlimentacionID,
	)
	return i, err
}

const crearRuta = `-- name: CrearRuta :one
INSERT INTO ruta_transporte (nombre_linea, frecuencia_aprox, precio, descripcion_ruta, cooperativa_id, sector_origen_id, sector_destino_id, parada_bus_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, nombre_linea, frecuencia_aprox, precio, descripcion_ruta, cooperativa_id, sector_origen_id, sector_destino_id, parada_bus_id
`

type CrearRutaParams struct {
	NombreLinea     string
	FrecuenciaAprox string
	Precio          float64
	DescripcionRuta string
	CooperativaID   int64
	SectorOrigenID  int64
	SectorDestinoID int64
	ParadaBusID     int64
}

func (q *Queries) CrearRuta(ctx context.Context, arg CrearRutaParams) (RutaTransporte, error) {
	row := q.db.QueryRowContext(ctx, crearRuta,
		arg.NombreLinea,
		arg.FrecuenciaAprox,
		arg.Precio,
		arg.DescripcionRuta,
		arg.CooperativaID,
		arg.SectorOrigenID,
		arg.SectorDestinoID,
		arg.ParadaBusID,
	)
	var i RutaTransporte
	err := row.Scan(
		&i.ID,
		&i.NombreLinea,
		&i.FrecuenciaAprox,
		&i.Precio,
		&i.DescripcionRuta,
		&i.CooperativaID,
		&i.SectorOrigenID,
		&i.SectorDestinoID,
		&i.ParadaBusID,
	)
	return i, err
}

const crearSector = `-- name: CrearSector :one
INSERT INTO sector (nombre)
VALUES (?)
RETURNING sector_id, nombre
`

func (q *Queries) CrearSector(ctx context.Context, nombre string) (Sector, error) {
	row := q.db.QueryRowContext(ctx, crearSector, nombre)
	var i Sector
	err := row.Scan(&i.SectorID, &i.Nombre)
	return i, err
}

const crearVivienda = `-- name: CrearVivienda :one
INSERT INTO vivienda (titulo, tipo_vivienda, precio, garantia, precio_garantia, direccion, luz, agua, amueblado, internet, bano_privado, numero_habitaciones, mascotas, genero_preferido, reglas_convivencia, telefono, email, estado, comentario, sector_id, proveedor_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING vivienda_id, titulo, tipo_vivienda, precio, garantia, precio_garantia, direccion, luz, agua, amueblado, internet, bano_privado, numero_habitaciones, mascotas, genero_preferido, reglas_convivencia, telefono, email, estado, comentario, sector_id, proveedor_id
`

type CrearViviendaParams struct {
	Titulo             string
	TipoVivienda       string
	Precio             float64
	Garantia           bool
	PrecioGarantia     float64
	Direccion          string
	Luz                bool
	Agua               bool
	Amueblado          bool
	Internet           bool
	BanoPrivado        bool
	NumeroHabitaciones int64
	Mascotas           bool
	GeneroPreferido    string
	ReglasConvivencia  string
	Telefono           string
	Email              string
	Estado             string
	Comentario         string
	SectorID           int64
	ProveedorID        int64
}

func (q *Queries) CrearVivienda(ctx context.Context, arg CrearViviendaParams) (Vivienda, error) {
	row := q.db.QueryRowContext(ctx, crearVivienda,
		arg.Titulo,
		arg.TipoVivienda,
		arg.Precio,
		arg.Garantia,
		arg.PrecioGarantia,
		arg.Direccion,
		arg.Luz,
		arg.Agua,
		arg.Amueblado,
		arg.Internet,
		arg.BanoPrivado,
		arg.NumeroHabitaciones,
		arg.Mascotas,
		arg.GeneroPreferido,
		arg.ReglasConvivencia,
		arg.Telefono,
		arg.Email,
		arg.Estado,
		arg.Comentario,
		arg.SectorID,
		arg.ProveedorID,
	)
	var i Vivienda
	err := row.Scan(
		&i.ViviendaID,
		&i.Titulo,
		&i.TipoVivienda,
		&i.Precio,
		&i.Garantia,
		&i.PrecioGarantia,
		&i.Direccion,
		&i.Luz,
		&i.Agua,
		&i.Amueblado,
		&i.Internet,
		&i.BanoPrivado,
		&i.NumeroHabitaciones,
		&i.Mascotas,
		&i.GeneroPreferido,
		&i.ReglasConvivencia,
		&i.Telefono,
		&i.Email,
		&i.Estado,
		&i.Comentario,
		&i.SectorID,
		&i.ProveedorID,
	)
	return i, err
}

const eliminarVivienda = `-- name: EliminarVivienda :execrows
DELETE FROM vivienda WHERE vivienda_id = ?
`

func (q *Queries) EliminarVivienda(ctx context.Context, viviendaID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, eliminarVivienda, viviendaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listarAlimentaciones = `-- name: ListarAlimentaciones :many

SELECT id, nombre_local, descripcion,ubicacion, direccion, horario_apertura, horario_cierre, telefono, tipo_comida, precio_promedio, provider_id FROM alimentacion
`

// ALIMENTACION --
func (q *Queries) ListarAlimentaciones(ctx context.Context) ([]Alimentacion, error) {
	rows, err := q.db.QueryContext(ctx, listarAlimentaciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alimentacion
	for rows.Next() {
		var i Alimentacion
		if err := rows.Scan(
			&i.ID,
			&i.NombreLocal,
			&i.Descripcion,
			&i.Ubicacion,
			&i.Direccion,
			&i.HorarioApertura,
			&i.HorarioCierre,
			&i.Telefono,
			&i.TipoComida,
			&i.PrecioPromedio,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarAplicarViviendas = `-- name: ListarAplicarViviendas :many

SELECT aplicar_vivienda_id, estudiante_id, vivienda_id, estado FROM aplicar_vivienda
`

// APLICAR VIVIENDA --
func (q *Queries) ListarAplicarViviendas(ctx context.Context) ([]AplicarVivienda, error) {
	rows, err := q.db.QueryContext(ctx, listarAplicarViviendas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AplicarVivienda
	for rows.Next() {
		var i AplicarVivienda
		if err := rows.Scan(
			&i.AplicarViviendaID,
			&i.EstudianteID,
			&i.ViviendaID,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarCooperativas = `-- name: ListarCooperativas :many

SELECT id, nombre, telefono, descripcion FROM cooperativa
`

// COOPERATIVAS --
func (q *Queries) ListarCooperativas(ctx context.Context) ([]Cooperativa, error) {
	rows, err := q.db.QueryContext(ctx, listarCooperativas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cooperativa
	for rows.Next() {
		var i Cooperativa
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Telefono,
			&i.Descripcion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarFotos = `-- name: ListarFotos :many

SELECT foto_id, url, vivienda_id FROM foto
`

// FOTOS --
func (q *Queries) ListarFotos(ctx context.Context) ([]Foto, error) {
	rows, err := q.db.QueryContext(ctx, listarFotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Foto
	for rows.Next() {
		var i Foto
		if err := rows.Scan(&i.FotoID, &i.Url, &i.ViviendaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMenuDiarios = `-- name: ListarMenuDiarios :many

SELECT id, fecha, alimentacion_id FROM menu_diario
`

// MENU DIARIO --
func (q *Queries) ListarMenuDiarios(ctx context.Context) ([]MenuDiario, error) {
	rows, err := q.db.QueryContext(ctx, listarMenuDiarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuDiario
	for rows.Next() {
		var i MenuDiario
		if err := rows.Scan(&i.ID, &i.Fecha, &i.AlimentacionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarParadas = `-- name: ListarParadas :many

SELECT id, nombre_parada, direccion, descripcion FROM paradas_bus
`

// PARADAS BUS--
func (q *Queries) ListarParadas(ctx context.Context) ([]ParadasBus, error) {
	rows, err := q.db.QueryContext(ctx, listarParadas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParadasBus
	for rows.Next() {
		var i ParadasBus
		if err := rows.Scan(
			&i.ID,
			&i.NombreParada,
			&i.Direccion,
			&i.Descripcion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPlatos = `-- name: ListarPlatos :many

SELECT id, nombre_plato, descripcion, categoria, precio, menu_diario_id FROM plato
`

// PLATOS --
func (q *Queries) ListarPlatos(ctx context.Context) ([]Plato, error) {
	rows, err := q.db.QueryContext(ctx, listarPlatos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plato
	for rows.Next() {
		var i Plato
		if err := rows.Scan(
			&i.ID,
			&i.NombrePlato,
			&i.Descripcion,
			&i.Categoria,
			&i.Precio,
			&i.MenuDiarioID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarResenas = `-- name: ListarResenas :many

SELECT id, comentario, calificacion, alimentacion_id FROM resena
`

// RESENAS --
func (q *Queries) ListarResenas(ctx context.Context) ([]Resena, error) {
	rows, err := q.db.QueryContext(ctx, listarResenas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resena
	for rows.Next() {
		var i Resena
		if err := rows.Scan(
			&i.ID,
			&i.Comentario,
			&i.Calificacion,
			&i.AlimentacionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarRutas = `-- name: ListarRutas :many

SELECT id, nombre_linea, frecuencia_aprox, precio, descripcion_ruta, cooperativa_id, sector_origen_id, sector_destino_id, parada_bus_id FROM ruta_transporte
`

// RUTAS DE TRANSPORTE --
func (q *Queries) ListarRutas(ctx context.Context) ([]RutaTransporte, error) {
	rows, err := q.db.QueryContext(ctx, listarRutas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RutaTransporte
	for rows.Next() {
		var i RutaTransporte
		if err := rows.Scan(
			&i.ID,
			&i.NombreLinea,
			&i.FrecuenciaAprox,
			&i.Precio,
			&i.DescripcionRuta,
			&i.CooperativaID,
			&i.SectorOrigenID,
			&i.SectorDestinoID,
			&i.ParadaBusID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSectores = `-- name: ListarSectores :many

SELECT sector_id, nombre FROM sector
`

// SECTORES --
func (q *Queries) ListarSectores(ctx context.Context) ([]Sector, error) {
	rows, err := q.db.QueryContext(ctx, listarSectores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sector
	for rows.Next() {
		var i Sector
		if err := rows.Scan(&i.SectorID, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarViviendas = `-- name: ListarViviendas :many

SELECT vivienda_id, titulo, tipo_vivienda, precio, garantia, precio_garantia, direccion, luz, agua, amueblado, internet, bano_privado, numero_habitaciones, mascotas, genero_preferido, reglas_convivencia, telefono, email, estado, comentario, sector_id, proveedor_id FROM vivienda
`

// VIVIENDAS --
func (q *Queries) ListarViviendas(ctx context.Context) ([]Vivienda, error) {
	rows, err := q.db.QueryContext(ctx, listarViviendas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vivienda
	for rows.Next() {
		var i Vivienda
		if err := rows.Scan(
			&i.ViviendaID,
			&i.Titulo,
			&i.TipoVivienda,
			&i.Precio,
			&i.Garantia,
			&i.PrecioGarantia,
			&i.Direccion,
			&i.Luz,
			&i.Agua,
			&i.Amueblado,
			&i.Internet,
			&i.BanoPrivado,
			&i.NumeroHabitaciones,
			&i.Mascotas,
			&i.GeneroPreferido,
			&i.ReglasConvivencia,
			&i.Telefono,
			&i.Email,
			&i.Estado,
			&i.Comentario,
			&i.SectorID,
			&i.ProveedorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
